allowBuilds:
  better-sqlite3: true
  esbuild: true
  less: true
  sharp: false
  workerd: true
overrides:
  "@playwright/experimental-ct-react>@vitejs/plugin-react": "6.1.1"
patchedDependencies:
  solid-js@1.9.14: patches/solid-js@1.9.14.patch
