name: Verify Changes

on:
  pull_request:
    branches: [main]

jobs:
  lint-code:
    uses: kad-products/platform/.github/workflows/lint-code.yaml@main
    permissions:
      contents: read
      packages: read
    secrets: inherit

  run-tests:
    uses: kad-products/platform/.github/workflows/run-tests.yaml@main
    permissions:
      contents: read
      packages: read
    secrets: inherit

  plan-github-config:
    uses: kad-products/platform/.github/workflows/plan-open-tofu.yaml@main
    with:
      app_name: ${{github.event.repository.name}}
      state_type: github
      state_name: setup
      working_directory: infra/github
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit    